export enum GameState {
  FIGHT_INIT = 'FIGHT_INIT',
  TURN_DECIDE = 'TURN_DECIDE',
  PLAYER_TURN = 'PLAYER_TURN',
  ENEMY_TURN = 'ENEMY_TURN',
  APPLY_EFFECT = 'APPLY_EFFECT',
  CHECK_END = 'CHECK_END',
  FIGHT_END = 'FIGHT_END',
  NONE = 'NONE',
}
